config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, :controllers => { registrations: 'customers/registrations', :passwords => "customers/passwords" }

  resources :customers, only: [:show, :edit, :update]

  resources :conversations, only: [:index]

  resources :customers, only: [:show, :edit, :update] do
    resources :conversations, only: [:index]
    resources :messages, only: [:index, :create, :destroy]
    resources :preferences, only: [:edit, :update]
  end

  resources :profiles, only: [:index]

  root 'pages#home'

  get '/success-stories' => 'pages#success_stories'
  get '/password-email-sent' => 'pages#password_email_sent'
  get '/confirmation-email-sent' => 'pages#confirmation_email_sent'

end

app/models/customer.rb
class Customer < ApplicationRecord

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  has_one :profile

  has_one :preference

  validates :username, :date_of_birth, presence: true
  validates :username, uniqueness: true
  validate :varify_age


  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable, :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :customer_languages, inverse_of: :customer
  has_many :languages, through: :customer_languages

  has_many :customer_desires, inverse_of: :customer
  has_many :desires, through: :customer_desires

  has_many :customer_ethnicities, inverse_of: :customer, dependent: :destroy
  has_many :ethnicities, through: :customer_ethnicities

  has_many :customer_religions, inverse_of: :customer
  has_many :religions, through: :customer_religions

  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :customer_languages
  accepts_nested_attributes_for :customer_desires
  accepts_nested_attributes_for :customer_ethnicities
  accepts_nested_attributes_for :customer_religions

  # has_many :sent_conversations, :foreign_key => :sender, :class_name => 'Conversation'
  # has_many :recipient_conversations, :foreign_key => :recipient, :class_name => 'Conversation'
  has_many :messages, dependent: :destroy
  has_many :sent_messages, :foreign_key => :sender, :class_name => 'Message'
  has_many :received_messages, :foreign_key => :recipient, :class_name => 'Message'

  after_create :create_starting_profile

  def new_token!
    SecureRandom.hex(16).tap do |random_token|
      ActiveRecord::Base.connection.execute("UPDATE customers SET login_token = '#{random_token}' WHERE id = #{id};")
      Rails.logger.info("Set new token for customer #{id}")
    end
  end

  private
  def varify_age
    unless self.date_of_birth.nil?
      if (self.date_of_birth.to_date + 18.years) > Date.today
        self.errors.add(:date_of_birth, "- You must be at least 18 years old to use this service")
      end
    end
  end

  def create_starting_profile
    Profile.create(customer_id: self.id, gender: "Male")
  end

  def crop_avatar
    self.profile.default_avatar.avatar.recreate_versions! if crop_x.present?
  end

end

app/controllers/customers/confirmations_controller.rb
class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  protected
  def after_sending_reset_password_instructions_path_for(resource_name)
    password_email_sent_path
  end
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
  def sign_up_params
    params.require(:customer).permit(:username, :email, :date_of_birth, :password, :password_confirmation, :current_password)
  end

  def account_update_params
    params.require(:customer).permit(:username, :email, :date_of_birth, :password, :password_confirmation, :current_password)
  end

  protected
  def after_inactive_sign_up_path_for(resource)
     confirmation_email_sent_path
  end
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def show
    @customer = Customer.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json {}
    end
  end

  def edit
    @customer = Customer.find(current_customer.id)
    @customer.build_profile unless @customer.profile
    @customer.build_preference unless @customer.preference
    @customer.customer_languages.build unless @customer.customer_languages
    @customer.customer_desires.build unless @customer.customer_desires
    @customer.profile.avatars.build
    @customer.customer_ethnicities.build unless @customer.customer_ethnicities

    respond_to do |format|
      format.html {}
      format.json {}
    end
  end

  def update
    @customer = Customer.find_by(id: params[:id])
    if @customer.update(customer_params)
      if params[:customer][:profile_attributes].present? && params[:customer][:profile_attributes][:default_avatar_id].present?
        @avatar = Avatar.find_by(id: params[:customer][:profile_attributes][:default_avatar_id])
        render :crop
      else
        redirect_to @customer, notice: "Successfully updated user."
      end
    else
      redirect_to @customer, notice: "Unable to update user."
    end
  end

  private

  def customer_params
    permitted = params.require(:customer).permit( :crop_x, :crop_y, :crop_h, :crop_w, profile_attributes: [:id, :smoker, :drinker, :level_of_education, :biography, :star_sign, :occupation, :imperial, :metric, :customer_id, :default_avatar_id,
      avatars_attributes: [:id, :avatar, :caption]], language_ids: [], desire_ids: [], ethnicity_ids: [], religion_ids: [] )
    unless permitted[:profile_attributes].nil?
      unless permitted[:profile_attributes][:avatars_attributes].nil?
        permitted[:profile_attributes][:avatars_attributes].each do |k,v|
          permitted[:profile_attributes][:avatars_attributes].delete k if v[:id].nil? && v[:avatar].nil?
        end
      end
    end
    permitted
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/crop.html.erb
<h1>Crop Avatar</h1>
<%= image_tag @avatar.avatar_url(:large), id: "cropbox" %>
<h4>Preview</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @avatar.avatar.url(:large), :id => "preview" %>
</div>
<%= form_for @customer do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  <div class="actions">
    <%= f.submit "Crop" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div id='edit-profile'>

  <h2>Edit Profile</h2>

  <%= form_for @customer do |f| %>
    <%= f.fields_for :profile do |builder| %>
      <div class="avatarContainer">
        <%= builder.fields_for :avatars do |avatar_builder| %>
          <div class="avatar">
            <div class="field">
              <% if avatar_builder.object.avatar.url.nil? %>
                Add <%= avatar_builder.label :avatar %>
              <% else %>
                <%= image_tag avatar_builder.object.avatar.url, {height: "50px"} %><br>
                Replace <%= avatar_builder.label :avatar %>
              <% end %>
              <%= avatar_builder.file_field :avatar %>
            </div>
            <div class="field">
              <%= avatar_builder.label :caption %>
              <%= avatar_builder.text_field :caption %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="avatarContainer">
        <% if builder.object.avatars.count > 0 %>
          <br>
          <%= builder.label :default_avatar_id %>
          <% if builder.object.avatars.count > 1 %>
            <% builder.object.avatars.each do |avatar| 
                next if avatar.avatar.url.nil? %>
              <div class="avatar center selectable">
                <%= image_tag avatar.avatar.url %><br>
                <%= builder.radio_button :default_avatar_id, avatar.id, value: builder.object.default_avatar_id == avatar.id, class: "hidden" %>
              </div>
            <% end %>
          <% else # Only one, so show them this as being the default %>
            <%= image_tag builder.object.avatars.first.avatar.url%><br>
            <%= builder.radio_button :default_avatar_id, avatar.id, value: builder.object.default_avatar_id == avatar.id, class: "hidden" %>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div id='edit-customer-languages'>
      <%= f.label "Languages" %>
      <%= f.collection_check_boxes :language_ids, Language.all, :id, :name, {}, {:multiple => true} %>
    </div>
    <div id='edit-customer-desires'>
      <%= f.label "Desires" %>
      <%= f.collection_check_boxes :desire_ids, Desire.all, :id, :name, {}, {:multiple => true} %>
    </div>
    <div id='edit-customer-ethnicities'>
      <%= f.label "Ethnicities" %>
      <%= f.collection_check_boxes :ethnicity_ids, Ethnicity.all, :id, :name, {}, {:multiple => true} %>
    </div>
    <div id='edit-customer-religions'>
      <%= f.label "Religions" %>
      <%= f.collection_check_boxes :religion_ids, Religion.all, :id, :name, {}, {:multiple => true} %>
    </div>
    <%= f.fields_for :profile do |p| %>
      <div id='edit-profile-biography'>
        <%= p.label :biography %>
        <%= p.text_area :biography %>
      </div>
      <div id='edit-profile-imperial'>
        <%= p.label :imperial %>
        <%= p.number_field :imperial %>
      </div>
      <div id='edit-profile-metric'>
        <%= p.label :metric %>
        <%= p.number_field :metric %>
      </div>
      <div id='edit-profile-occupation'>
        <%= p.label :occupation %>
        <%= p.select :occupation, ['-', 'Architect', 'Curator', 'Dog Walker', 'Fashion Designer', 'Marine Biologist', 'Party Planner', 'Private Detective', 'Robotics Engineer', 'Veterinarian', 'Unemployed']%>
      </div>
      <div id='edit-profile-smoker'>
        <%= p.label :smoker %>
        <%= p.select :smoker, ['-', 'Smoker', 'Non-Smoker', 'Social Smoker']%>
      </div>
      <div id='edit-profile-drinker'>
        <%= p.label :drinker %>
        <%= p.select :drinker, ['-', 'Teetotaller', 'Peer Pressure Drinker', 'Raving Alcoholic', 'Gin Guzzler']%>
      </div>
      <div id='edit-profile-education'>
        <%= p.label :level_of_education %>
        <%= p.select :level_of_education, ['-', 'Dumb', 'Primary', 'Secondary', 'Further', 'Higher', 'Genius']%>
      </div>
      <div id='edit-profile-star-sign'>
        <%= p.label :star_sign %>
        <%= p.select :star_sign, ['-', 'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces']%>
      </div>
    <% end %>

    <div id='edit-customer-submit'>
      <%= f.submit %>
    </div>
  <% end %>

</div>

app/views/customers/show.html.erb
<span id="user-id" data-id="<%= @customer.id %>"></span>
<% puts @customer.preference.metric %>

  <div class="row">
    <div class="col-md-4">
      <div class="sidebar">
        <div class="row">
          <div class="col-md-12">
            <img src="<%= @customer.profile.default_avatar.avatar_url(:thumb) unless @customer.profile.default_avatar.nil? %>" class="img-circle" />
          </div>
          <div class="row small-view">
            <div class="col-md-11">
              <h1 class="customer-name"><%= @customer.username.capitalize %></h1>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="stats">
              <div class="row">
                <div class="col-md-10 col-md-offset-1">
                  <div class="row well well-sm">
                    <div class="col-md-4 keys">
                      <p>Gender:</p>
                      <p>Age:</p>
                      <p>Weight:</p>
                      <p>Ethnicity:</p>
                      <p>Occupation:</p>
                      <p>Education:</p>
                      <p>Religion:</p>
                      <p>Star sign:</p>
                      <p>Drinker:</p>
                      <p>Smoker:</p>
                    </div>
                    <div class="col-md-8 values">
                      <p><%= @customer.profile.gender unless @customer.profile.gender.nil? %></p>
                      <p><%= (Date.today - @customer.date_of_birth).to_i / 365 %></p>
                      <p><%= @customer.preference.metric ? "#{@customer.profile.metric}kg" : "#{@customer.profile.imperial}lb" %></p>
                      <p><%#= @customer.profile.ethnicity unless @customer.profile.ethnicity.nil? %>European</p>
                      <p><%= @customer.profile.occupation unless @customer.profile.occupation.nil? %></p>
                      <p><%= @customer.profile.level_of_education unless @customer.profile.level_of_education.nil? %></p>
                      <p><%#= @customer.profile.religions unless @customer.profile.religion.nil? %>Amish</p>
                      <p><%= @customer.profile.star_sign unless @customer.profile.star_sign.nil? %></p>
                      <p><%= @customer.profile.drinker unless @customer.profile.drinker.nil? %></p>
                      <p><%= @customer.profile.smoker unless @customer.profile.smoker.nil? %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">

          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="profile-main">
        <div class="row large-view">
          <div class="col-md-11">
            <h1 class="customer-name"><%= @customer.username.capitalize %></h1>
          </div>
        </div>
        <div class="row">
          <div class="col-md-11 well">

            <h2>About Me</h2>
            <span class="edit-button glyphicon glyphicon-pencil"></span>
            <p><%= @customer.profile.biography unless @customer.profile.biography.nil? %></p>
            <textarea id="biography" class="hidden" rows="10"></textarea>
            <button type="submit" class="hidden">Save</button>

          </div>
        </div>
        <div class="row">
          <div class="col-md-11 well">
            <h4 class="profile-caption">LOOKING FOR</h4>
            <ul>
              <% @customer.desires.each do |desire| %>
                <li><%= desire.name %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">

          </div>
        </div>
      </div>
      <div class="edit-profile-link">
        <%= link_to edit_customer_path do %>
          <p>EDIT PROFILE</p>
        <% end %>
      </div>
    </div>
  </div>


<% unless @customer.id == current_customer.id %>
  <%= link_to "Send message", root_url, id: "open-message-modal-button" %>
<% end %>

<div id="message-modal">
  <input type="textarea" id="modal-message-text-area" />
  <input type="submit" id="send-message-button" value="Send" />
</div>