config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, :controllers => { registrations: 'customers/registrations', :passwords => "customers/passwords" }

  resources :customers, only: [:show, :edit, :update]

  resources :conversations, only: [:index]

  resources :customers, only: [:show, :edit, :update] do
    resources :conversations, only: [:index]
    resources :messages, only: [:index, :create, :destroy]
    resources :preferences, only: [:edit, :update]
  end

  resources :profiles, only: [:index]

  root 'pages#home'

  get '/success-stories' => 'pages#success_stories'
  get '/password-email-sent' => 'pages#password_email_sent'
  get '/confirmation-email-sent' => 'pages#confirmation_email_sent'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :profile, required: false

  mount_uploader :avatar, AvatarUploader
end

app/models/customer.rb
class Customer < ApplicationRecord

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  has_one :profile

  has_one :preference

  validates :username, :date_of_birth, presence: true
  validates :username, uniqueness: true
  validate :varify_age


  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable, :confirmable,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :customer_languages, inverse_of: :customer
  has_many :languages, through: :customer_languages

  has_many :customer_desires, inverse_of: :customer
  has_many :desires, through: :customer_desires

  has_many :customer_ethnicities, inverse_of: :customer, dependent: :destroy
  has_many :ethnicities, through: :customer_ethnicities

  has_many :customer_religions, inverse_of: :customer
  has_many :religions, through: :customer_religions

  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :customer_languages
  accepts_nested_attributes_for :customer_desires
  accepts_nested_attributes_for :customer_ethnicities
  accepts_nested_attributes_for :customer_religions

  # has_many :sent_conversations, :foreign_key => :sender, :class_name => 'Conversation'
  # has_many :recipient_conversations, :foreign_key => :recipient, :class_name => 'Conversation'
  has_many :messages, dependent: :destroy
  has_many :sent_messages, :foreign_key => :sender, :class_name => 'Message'
  has_many :received_messages, :foreign_key => :recipient, :class_name => 'Message'

  after_create :create_starting_profile

  def new_token!
    SecureRandom.hex(16).tap do |random_token|
      ActiveRecord::Base.connection.execute("UPDATE customers SET login_token = '#{random_token}' WHERE id = #{id};")
      Rails.logger.info("Set new token for customer #{id}")
    end
  end

  private
  def varify_age
    unless self.date_of_birth.nil?
      if (self.date_of_birth.to_date + 18.years) > Date.today
        self.errors.add(:date_of_birth, "- You must be at least 18 years old to use this service")
      end
    end
  end

  def create_starting_profile
    Profile.create(customer_id: self.id, gender: "Male")
  end

  def crop_avatar
    self.profile.default_avatar.avatar.recreate_versions! if crop_x.present?
  end

end

app/models/customer_desire.rb
class CustomerDesire < ApplicationRecord

  belongs_to :customer
  belongs_to :desire

end

app/models/customer_ethnicity.rb
class CustomerEthnicity < ApplicationRecord

  belongs_to :customer
  belongs_to :ethnicity

end

app/models/customer_language.rb
class CustomerLanguage < ApplicationRecord

  belongs_to :customer
  belongs_to :language

end

app/models/customer_profile.rb
class CustomerProfile < ApplicationRecord
  self.primary_key = 'id'
  has_many :customer_ethnicities, foreign_key: :customer_id
  has_many :ethnicities, through: :customer_ethnicities
end

app/models/customer_religion.rb
class CustomerReligion < ApplicationRecord

  belongs_to :customer
  belongs_to :religion

end

app/models/desire.rb
class Desire < ApplicationRecord

  has_many :customer_desires, inverse_of: :desire
  has_many :customers, through: :customer_desires

end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord

  has_many :customer_ethnicities, inverse_of: :ethnicity
  has_many :customers, through: :customer_ethnicities

end

app/models/featured_profile.rb
class FeaturedProfile < ApplicationRecord
  belongs_to :profile

  def self.check_if_featured_profiles_need_refreshing
    if FeaturedProfile.count < 4 || FeaturedProfile.first.created_at + 1.days < Time.now
      choose_new_featured_profiles
    end
  end

  def self.choose_new_featured_profiles
  old_featured_customers = FeaturedProfile.all.map{|fp| fp.profile.customer}
  featured_customers = []
  men = 0
  women = 0
  FeaturedProfile.destroy_all
    while featured_customers.count < 4
      number = rand(Customer.count)
      chosen = Customer.all[number]
      unless featured_customers.include?(chosen) ||
      old_featured_customers.include?(chosen) ||
      (chosen.profile.gender == "Male" && men >= 2) ||
      (chosen.profile.gender == "Female" && women >= 2)
        featured_customers << chosen
        if chosen.profile.gender == "Male"
          men += 1
        elsif chosen.profile.gender == "Female"
          women += 1
        end
      end
    end
    featured_customers.each do |fc|
      FeaturedProfile.create(profile_id: fc.profile.id)
    end
  end


end

app/models/language.rb
class Language < ApplicationRecord

  has_many :customer_languages, inverse_of: :language
  has_many :customers, through: :customer_languages

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :customer
  belongs_to :receiver, class_name: "Customer"
  belongs_to :sender, class_name: "Customer"

  def self.conversation_messages(customer1, customer2)
    Message.where("
      (sender_id = #{customer1.id.to_i} AND recipient_id = #{customer2.id.to_i})
      OR (sender_id = #{customer2.id.to_i} AND recipient_id = #{customer1.id.to_i})
    ")
  end

end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :customer
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :customer

  belongs_to :default_avatar, class_name: "Avatar", required: false

  has_many :avatars
  accepts_nested_attributes_for :avatars

  before_save :set_default_avatar

  private

  def set_default_avatar
    if self.avatars.count == 1
      self.default_avatar = self.avatars.first
    end
  end

  def self.list_genders
    ["Male", "Female"]
  end

  def self.list_smokers
    ['Smoker', 'Non-Smoker', 'Social Smoker']
  end  

end

app/models/religion.rb
class Religion < ApplicationRecord

  has_many :customer_religions, inverse_of: :religion
  has_many :customers, through: :customer_religions

end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wegotsingles</title>
  <%= stylesheet_link_tag 'application', params[:controller], media: 'all' %>
  <%= javascript_include_tag 'application', params[:controller] %>
  <%= javascript_include_tag 'jquery.timeago.js' %>
  <%= stylesheet_link_tag 'jquery.Jcrop.css' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="container">
  	<header>
      <div class="row">
        <div class="col-md-4 col-sm-12">
      		<%= link_to root_url, class: "logo" do %>
            <i id="main-logo">We Got Singles</i>
          <% end %>
        </div>
        <div class="col-md-8 col-sm-12">
          <ul class="menu">
            <li>
              <%= link_to "HOME", root_url %>
            </li>
            <% if customer_signed_in? %>
              <li><%= link_to "FIND LOVE", profiles_path %></li>
            <% else %>
              <li><%= link_to "ABOUT" %></li>
            <% end %>
            <% if customer_signed_in? %>
              <li>
                <%= link_to "MESSAGES", customer_conversations_path(current_customer) %>
              </li>
            <% else %>
              <li><%= link_to "PAGES" %></li>
            <% end %>
            <% if customer_signed_in? %>
              <li class="nav-item dropdown">
                <%= link_to "PROFILE", customer_path(current_customer), {class: "nav-link dropdown-toggle", :'data-toggle' => "dropdown", role: "button", :'aria-haspopup' => "true", :'aria-expanded' => "false"} %>
                <div class="dropdown-menu">
                  <%= link_to "Profile", customer_path(current_customer), class: "dropdown-item" %>
                  <%= link_to "Preferences", edit_customer_preference_path(customer_id: current_customer.id, id: current_customer.preference.id), class: "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li><%= link_to "SUCCESS STORIES", success_stories_path %></li>
            <% end %>
            <% if customer_signed_in? %>
              <li class="sign-out"><%= link_to "SIGN OUT", destroy_customer_session_path, method: :delete %></li>
            <% else %>
              <li ><%= link_to "SIGN IN", new_customer_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>

	<main>
		<%= yield %>
	</main>


    <footer>
      <p>&#169; 2016 We Got Coders</p>
    </footer>
  </div>

</body>
</html>

app/views/pages/confirmation_email_sent.html.erb
<p>An email has been sent to you with instructions on how to complete your registration</p>

app/views/pages/home.html.erb
  <div class="row">
    <div class="col-md-12">
      <div class="home-jumbotron">
        <div id="hp-jt-carousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#hp-jt-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#hp-jt-carousel" data-slide-to="1"></li>
            <li data-target="#hp-jt-carousel" data-slide-to="2"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active">
              <img id="deadpool" src="/assets/Deadpool-and-Vanessa.jpg" alt="Deadpool and Vanessa">
            </div>
            <div class="item">
              <img id="superman" src="/assets/superman.jpg" alt="Superman and Lois">
            </div>
            <div class="item">
              <img id="shamy" src="/assets/shamy-kiss.jpg" alt="Sheldon and Amy kiss">
            </div>
          </div>
        </div>
      </div>
      <div class="home-jumbotron-text">
        <% unless customer_signed_in? %>
          <h1>JOIN TODAY!</h1>
          <%= link_to new_customer_registration_path do %>
            <p>REGISTER</p>
          <% end %>
        <% else %>
          <h1>Welcome, <%= current_customer.username.capitalize %>!<h1>
        <% end %>
      </div>
    </div>
  </div>



  <div class="row">
    <div class="col-md-12">
      <div class="home-featured-profiles">
        <h2 class="feat">FEATURED PROFILES</h2>
        <div class="row">
          <div class="feature-prof col-md-3 col-sm-6">
            <div class="profile">
            </div>
          </div>
          <div class="feature-prof col-md-3 col-sm-6">
            <div class="profile">
            </div>
          </div>
          <div class="feature-prof col-md-3 col-sm-6">
            <div class="profile">
            </div>
          </div>
          <div class="feature-prof col-md-3 col-sm-6">
            <div class="profile">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="row">
    <div class="col-md-12">
      <div class="home-stories"></div>
      <div class = "feat-stories">
        <h2 class="feat">FEATURED STORIES</h2>

        <div id="hp-jfs-carousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#hp-fs-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#hp-fs-carousel" data-slide-to="1"></li>
            <li data-target="#hp-fs-carousel" data-slide-to="2"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active story">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae ipsum vitae quam porta accumsan. In tincidunt erat lacus, quis tincidunt nulla aliquet ac. Vivamus luctus, neque eu euismod sollicitudin, quam lorem dictum leo, ac rutrum magna leo non orci. Aliquam sit amet risus nec quam dignissim sagittis. Donec pretium, elit quis faucibus viverra, magna odio imperdiet elit, nec ornare lectus neque pharetra mauris.</p>
              <cite>Fred & Tina</cite>
            </div>
            <div class="item story">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae ipsum vitae quam porta accumsan. In tincidunt erat lacus, quis tincidunt nulla aliquet ac. Vivamus luctus, neque eu euismod sollicitudin, quam lorem dictum leo, ac rutrum magna leo non orci. Aliquam sit amet risus nec quam dignissim sagittis. Donec pretium, elit quis faucibus viverra, magna odio imperdiet elit, nec ornare lectus neque pharetra mauris.</p>
              <cite>Barvis & Edwina</cite>
            </div>
            <div class="item story">
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae ipsum vitae quam porta accumsan. In tincidunt erat lacus, quis tincidunt nulla aliquet ac. Vivamus luctus, neque eu euismod sollicitudin, quam lorem dictum leo, ac rutrum magna leo non orci. Aliquam sit amet risus nec quam dignissim sagittis. Donec pretium, elit quis faucibus viverra, magna odio imperdiet elit, nec ornare lectus neque pharetra mauris.</p>
              <cite>George & Sally</cite>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/password_email_sent.html.erb
<p>An email has been sent to you with instructions on how to reset your password</p>

app/views/pages/success_stories.html.erb
  <div class="success_stories">
    <div class="display col-md-12">
      <div class="feat">
        <h1>SUCCESS STORIES</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 stories">
          <img src="assets/kateleo.jpg" alt="Kate and Leo" />
          <p>I used WeGotSingles when I was studying abroad in England one semester. I actually met a guy who went to the same school as me, but without WeGotSingles, we never would've crossed paths! We hit it off right away, and now we've been dating for almost four days.</p>
      </div>
    </div>
    <div class="heart"></div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 stories">
          <img src="assets/xmen.jpg" alt="Raven and Beast"/>
          <p>Once I was on WeGotSingles when a match messaged me, 'I will feed u until ur in a food coma every time.' This sounded like an absolute dream for me—someone who very passionately loves food. Nothing happened besides that, but the moment was magical in and of itself. And if that wasn't enough, his first name was Beast.</p>
      </div>
    </div>
    <div class="heart"></div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 stories">
          <img src="assets/brokebackmountain.jpg" alt="Heath and Jake"/>
          <p>A month after going on a seriously bad Tinder date (the guy was cheating on his boyfriend with me—cute), I met up with a different WeGotSingles guy at a local bar. I was completely wasted, brought my friends with me, and made a total fool out of myself. My friends thought he was 30 and didn't know I'd met him on WeGotSingles. But he looked past my drunkenness and took me on an actual date the next night. We hit it off, my friends loved him, and the rest was history—more than two years later, we're as happy as ever.</p>
      </div>
    </div>
  </div>